-- GENERATED BY CHATGPT
-- ROLE
INSERT INTO role (rola_id, nazwa) VALUES
(1, 'admin'),
(2, 'zawodnik');

-- USERS
INSERT INTO users (user_id, imie, nazwisko, email, haslo, rola_id) VALUES
(1, 'Jan', 'Kowalski', 'jan@example.com', 'hash1', 2),
(2, 'Anna', 'Nowak', 'anna@example.com', 'hash2', 2),
(3, 'Admin', 'System', 'admin@example.com', 'adminhash', 1);

-- ZAWODNIK
INSERT INTO zawodnik (zawodnik_id, user_id, numer_licencji, kategoria_wiekowa, numer_kontaktowy) VALUES
(1, 1, 12345, 1, '+48111111111'),
(2, 2, 67890, 1, '+48222222222');

-- GOKART
INSERT INTO gokart (gokart_id, nazwa, status) VALUES
(1, 'Kart #1', 1),
(2, 'Kart #2', 1);

-- TOR
INSERT INTO tor (tor_id, nazwa, lokalizacja) VALUES
(1, 'Tor Katowice', 'Katowice'),
(2, 'Tor Krakow', 'Krakow');

-- WYDARZENIE
INSERT INTO wydarzenie (wydarzenie_id, nazwa, data, typ, tor_id) VALUES
(1, 'Weekend Race', '2026-04-20 10:00:00', 1, 1);

-- WYSCIG
INSERT INTO wyscig (wyscig_id, warunki_pogodowe, wydarzenie_id) VALUES
(1, 1, 1);

-- UDZIAL
INSERT INTO udzial (udzial_id, pozycja_startowa, pozycja_koncowa, zawodnik_id, gokart_id, wyscig_id) VALUES
(1, 1, 2, 1, 1, 1),
(2, 2, 1, 2, 2, 1);

-- OKRAZENIA
INSERT INTO okrazenie (okrazenie_id, numer_okrazenia, czas_okrazenia, udzial_id) VALUES
(1, 1, 75.321, 1),
(2, 2, 74.210, 1),
(3, 1, 73.999, 2),
(4, 2, 72.888, 2);

-- PLAN
INSERT INTO plan (plan_id, status, wydarzenie_id, zawodnik_id, gokart_id) VALUES
(1, 1, 1, 1, 1),
(2, 1, 1, 2, 2);

-- PODZESPOL
INSERT INTO podzespol (podzespol_id, typ, motogodziny, przebieg, data_montazu, status, gokart_id) VALUES
(1, 1, 100, 500, '2026-01-01 00:00:00', 1, 1);

-- SERWIS
INSERT INTO serwis (serwis_id, data_serwisu, opis, typ, podzespol_id, user_id) VALUES
(1, '2026-04-10 12:00:00', 'Wymiana oleju', 1, 1, 3);

-- USTERKA
INSERT INTO usterka (usterka_id, opis, data_wykrycia, status, podzespol_id) VALUES
(1, 'Zuzyte hamulce', '2026-04-15 09:00:00', 1, 1);

-- WYMIANA
INSERT INTO wymiana (wymiana_id, data_wymiany, opis, podzespol_id, user_id) VALUES
(1, '2026-04-16 10:00:00', 'Nowe klocki hamulcowe', 1, 3);

-- POWIADOMIENIE
INSERT INTO powiadomienie (powiadomienie_id, tresc, data_utworzenia, status, user_id) VALUES
(1, 'Nowy serwis wykonany', '2026-04-16 11:00:00', 'N', 1);
